version: '2'

tasks:

  setup:
    cmds:
      - cp deps/bin/x64/raylib.dll ./raylib.dll
    silent: true

  build:
    cmds:
      - nim c -o:./xd.exe src/xd.nim 
    sources:
      - ./src/*.nim
      - ./src/**/.nim
    generates:
      - xd{{exeExt}}

  run:
    cmds:
      - nim c -o:./xd.exe -r src/xd.nim

  release:
    cmds:
      - nimble build
    silent: true

  clean:
    cmds:
      - rm *.exe
      - rm ./raylib.dll
