version: '2'

tasks:

  setup:
    cmds:
      - echo "todo - setup dependencies"
    silent: true

  build:
    cmds:
      - echo "todo"
    sources:
      - ./*.nim
      - ./**/.nim
    generates:
      - xd{{exeExt}}

  release:
    cmds:
      - echo "todo - bundle release"
    silent: true

  clean:
    cmds:
      - rm *.exe
