version: '2'

tasks:

  setup:
    cmds:
      - cp deps/bin/x64/raylib.dll ./raylib.dll
    silent: true

  install:
    cmds:
      - nimble install

  build:
    cmds:
      - nim c -o:./xd{{exeExt}} src/xd.nim 
    sources:
      - ./src/*.nim
      - ./src/**/.nim
    generates:
      - xd{{exeExt}}

  test:
    cmds:
      - nimble test

  run:
    cmds:
      - nim c -o:./xd{{exeExt}} -r src/xd.nim

  release:
    cmds:
      - nim c -d:release --opt:size --passL:-s -o:./xd{{exeExt}} src/xd.nim

  clean:
    ignore_error: true
    silent: true
    cmds:
      - rm *.xd{{exeExt}}
      - rm *.exe
      - rm ./raylib.dll
